### ISSUE TITLE
Add basic configuration and info files

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-igorkruglyak#13]
* [ ] `README.md`, stating your project title, styled with Markdown
* [ ] `LICENSE` file. Find a template for it in plain text or Markdown format. You may use MIT license for simplicity
* [ ] `.gitattributes`. Find some template for your repo on github
* [ ] `.gitignore`. Find a typical template for your language (Python, Vim, Linux etc.) @ gitignore.io

You'll need to push a new branch (e.g. `features/3-initial-config`) with atomic commits and [create a PR](https://help.github.com/en/articles/creating-a-pull-request) **referencing this issue**.

**Comment by igorkruglyak** [comment]
Ніяк не можу розібратись з цією проблемою:
В новій гілці додав 
.gitattributes
.gitignore
коли ввів python -m pre_commit run --all-files
отримав
Check Yaml...............................................................Passed
Debug Statements (Python)............................(no files to check)Skipped
Tests should end in _test.py.........................(no files to check)Skipped
Fix requirements.txt.................................(no files to check)Skipped
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Failed
hookid: end-of-file-fixer

Files were modified by this hook. Additional output:

Fixing .gitignore

Check docstring is first.............................(no files to check)Skipped
Fix double quoted strings............................(no files to check)Skipped
Check python ast.....................................(no files to check)Skipped
Don't commit to branch...................................................Passed
Check for merge conflicts................................................Passed
flake8...............................................(no files to check)Skipped
Add trailing commas..................................(no files to check)Skipped
CRLF end-lines checker...................................................Passed
CRLF end-lines remover...................................................Passed
No-tabs checker..........................................................Passed
Tabs remover.............................................................Passed
Verifying PEP257 Compliance..........................(no files to check)Skipped
mypy.................................................(no files to check)Skipped
PyLint...............................................(no files to check)Skipped

Що може бути не так з .gitignore?
Ось сам що в .gitignore
https://pastebin.com/u2v0QGa5
Підкажи, будь ласка, де я затупив.

**Comment by webknjaz** [comment]
кінець файла автоматично виправився пре-комітом. закомітити змінений треба.
не треба мені сніпети слати. треба ПР.

**Comment by webknjaz** [comment]
раджу ще питати це все у чаті загальному.

**Comment by igorkruglyak** [comment]
> кінець файла автоматично виправився пре-комітом. закомітити змінений треба.
> не треба мені сніпети слати. треба ПР.

Дякую.
