### ISSUE TITLE
Configure integration of Heroku deployment with GitHub

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-igorkruglyak#20]
It's a follow-up for #19.

* [x] Accept invitation to [this organization](https://github.com/kpi-web-guild)
 * optionally make your membership public, so that there will be hat logo displayed on your profile page ^^
* [x] Choose [this repo](https://github.com/kpi-web-guild/django-girls-blog-igorkruglyak) in `Heroku Dashboard` on `Deploy` page
* [ ] Make [`master` branch](https://github.com/kpi-web-guild/django-girls-blog-igorkruglyak/tree/master) be deployed on update once the tests pass

**Comment by igorkruglyak** [comment]
Partially solved by PR #26 (70c07303abe757f00fbfed06c9f211e7fd5225fb)

**Comment by webknjaz** [comment]
Tutorial URL: https://tutorial-extensions.djangogirls.org/en/heroku/
