### ISSUE TITLE
Hard reset the master branch

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-igorkruglyak#6]
There was no task of committing anything to `master`. You have to learn PRs and branching first. So return it to the initial state in the remote repo. You can keep the backup of your commit in a separate branch locally, though.

P.S. Files like `.vscode/` and `db.sqlite3` must be never committed into a Git repo. Binary blobs are bad for the tree and dev-specific configs shouldn't be stored in the shared space. Committing pyc compiled modules is also bad. Virtualenv shouldn't be committed either. The repo is for the actual source code, not something that could be generated from it — that's garbage.

**Comment by igorkruglyak** [comment]
close #6
ok

**Comment by webknjaz** [comment]
You just added a new commit, I want you to completely wipe out the branch on remote

**Comment by igorkruglyak** [comment]
git branch -d master ?

**Comment by webknjaz** [comment]
That command works with a local repo, I want you to clean up the remote.

**Comment by webknjaz** [comment]
If you experience difficulties, ask for help in Gitter chat :)

**Comment by igorkruglyak** [comment]
just write what i have to do for that. I'm already confused.

**Comment by webknjaz** [comment]
`git push -d origin master`

**Comment by igorkruglyak** [comment]
result:
To github.com:kpi-web-guild/django-girls-blog-igorkruglyak.git
 ! [remote rejected] master (refusing to delete the current branch: refs/heads/master)
error: failed to push some refs to 'git@github.com:kpi-web-guild/django-girls-blog-igorkruglyak.git'

**Comment by webknjaz** [comment]
Alright, GitHub probably blocks deleting the default branch. So just rewrite it with an empty commit.
```console
git rm -rf * .*
git commit --allow-empty -m "Initial commit"
git push origin master:master --force
```

But first, complete https://github.com/kpi-web-guild/django-girls-blog-igorkruglyak/issues/7 because your local Git config is clearly incomplete.

**Comment by igorkruglyak** [comment]
Thank you very much! I cleaned it

**Comment by webknjaz** [comment]
Oh, we missed one flag. It's not clean yet. There's 4 commits in master.
```console
git reset --hard HEAD~3
git rm -rf * .*
git commit --allow-empty -m "Initial commit"
git push origin master:master --force
```

**Comment by igorkruglyak** [comment]
ok. now the correct result?

**Comment by webknjaz** [comment]
You still have two commits on master. Try using `git rebase --interactive` to squash them into one.

**Comment by igorkruglyak** [comment]
I did not succeed

`git rebase --interactive
Successfully rebased and updated refs/heads/master.
git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
git log
commit 6f17c02b333dced65bc42ff1ea8f231fc62449d6 (HEAD -> master, origin/master)
Author: Igor Kruglyak <igorkruglyak@gmail.com>
Date:   Tue Jun 4 00:10:51 2019 +0300

    Initial commit

commit 072ebf44fb82ed6eadf63371b70b5b2a295395f3
Author: igorkruglyak <igorkruglyak.com>
Date:   Sat May 25 16:17:25 2019 +0300

    first commit`

**Comment by webknjaz** [comment]
@igorkruglyak it looks like you didn't specify `HEAD~2`

**Comment by webknjaz** [comment]
Treat this task as a follow-up for #4. IRL you'll face way more complicated things with Git. My main objective is making you able to solve such problems by yourself.

**Comment by igorkruglyak** [comment]
it is right?

**Comment by webknjaz** [comment]
Great, I've protected the `master` branch. Now you cannot push there and will need to follow the common flow with branches and PR reviews :)

**Comment by webknjaz** [comment]
I hope you learned something new for yourself :)

**Comment by igorkruglyak** [comment]
Oh yeah :)
